### ISSUE TITLE
Le CR de l'AGO 2016 n'a pas la bonne licence

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/documents-association#19]
L'article : https://zestedesavoir.com/articles/1254/assemblee-generale-ordinaire-2016-de-zeste-de-savoir/

La licence est une CC-BY SA , contrairement a ce qui est marqué dans le RI.

**Comment by gustavi** [comment]
Pour le coup c'est un réflexe de mettre mes contenus en SA. C'est corrigé, tu n'étais pas obligé de créer un ticket sur le GitHub ;)

**Comment by firm1** [comment]
C'etait surtout pour pas oublier (et peut etre qu'il y'avait une vrai raison)

Merci.
