### ISSUE TITLE
Licence des documents de l'association

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/documents-association#6]
Aujourd'hui pas de licence sur ces documents, il faudrait statuer là dessus.

Je propose du CC BY-SA, à discuter.

**Comment by SpaceFox** [comment]
Ce serait pas mal qu'on harmonise, d'ailleurs :
- [Les CGU](https://zestedesavoir.com/pages/cgu/) sont sous licence CC-BY
- [La page des cookies](https://zestedesavoir.com/pages/cookies/) est sous licence CC-BY-NC-SA
- [Les articles rédigés au nom de ZdS](https://zestedesavoir.com/articles/?tag=zds) sont sous licence… aléatoire ? J'ai pas vérifié, mais je crois qu'on a au moins un article sous chaque licence qu'on propose !

Je suggère donc qu'on rationalise tout ça en passant chaque contenu sous une licence libre, connue et très réutilisable, donc sous CC-BY.

Je ne sais pas ce que ça implique pour les contenus déjà existants, je suppose qu'il faut l'accord des auteurs ?

**Comment by gustavi** [comment]
Pour les articles de ZdS (sur les versions) j'essaye de toujours les mettes en CC-BY-SA.

**Comment by cgabard** [comment]
Pour les CGU, techniquement, c'est Arius l'auteur mais ne l'a t'il pas fait au nom de l'asso ?

Pour celle des cookies, elle vient d'où ? La recette je sais mais le reste ?

Pour rationaliser ça ne peux t'on pas ajouter un paragraphe dans le RI qui stipule que tous les documents public produits par l'association et dans le cadre de son fonctionnement sont sous CC-BY ?

**Comment by gustavi** [comment]
@cgabard est-ce que cela implique aussi la documentation de ZdS ?

**Comment by SpaceFox** [comment]
La page des cookies est de moi, recette comprise.

**Comment by cgabard** [comment]
@gustavi   pour moi non, elle elle est produite par les dev. Cependant ce serait bien que les dev s'accordent dessus et fixent clairement la licence du contenu existant et précisent que toute nouvelle contribution se fait sous cette licence. C'est dans les but de l'asso de promouvoir du contenu libre, ce serait bien qu'on se l'impose a nous meme à tous les niveaux

**Comment by gustavi** [comment]
Si je ne dis pas de bêtise elle est dans le même dépôt que le code donc en GNU GPL 3 non ?

**Comment by cgabard** [comment]
En l,'absence d'autre chose oui probablement mais ce serait pas déconnant de faire passer la documentation sur une licence adapté

**Comment by gustavi** [comment]
J'ai ouvert un sujet avec des informations en plus de celles de @SpaceFox et pour en discuter sur le forum : https://zestedesavoir.com/forums/sujet/5645/licence-des-documents-produits-par-lassociation-le-staff-et-les-dev/
